**Análise de Sentimentos**

 Exemplos de Utilização:
* Monitorar o humor da Web com relação a sua marca ou algum produto.
* Classificação automática de pesquisas de opiniões (positivas ou negativas).
* Call centers para analisar ligações telefônicas entre atendentes e clientes.
* Políticos para acompanhar o "Humor da Web" sobre seus pronunciamentos ou acontecimentos que os envolve.

**Léxicos**

Os léxicos são bases de conhecimento criadas manualmente ou de forma automatizada para atender um domínio específico (Linguística, Psicologia, Direito, etc.).
Vantagem: não há necessidade de rotular dados para treinamento.
Desvantagem:  léxicos são limitados a idioma e tamanho da base de conhecimento.

**SentilexPT**

É um léxico para o idioma Português possui 6531 adjetivos com informações de polaridade, alvo do sentimento e método de atribuição de polaridade.
tipo: PoS
Gênero: GN
alvo do sentimento: TG=HUM
polaridade: POL ( 1 ou -1 ou 0)
como a polaridade foi atribuida: ANOT

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
#pip install google-play-scraper

In [ ]:
#monta Google Drive para acesso aos arquivos
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
#importar biblioteca numpy, pandas, io
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import io

In [38]:
# Importar SentilexPT2
nomes=["palavra", "a", "polaridade", "b", "x","y"]
df = pd.read_csv("/content/drive/MyDrive/datasets/SentiLex-lem-PT02.csv", sep=';', names=nomes)
df.head(100)

              palavra          a polaridade          b    x   y
0     à-vontade.PoS=N  TG=HUM:N0   POL:N0=1   ANOT=MAN  NaN NaN
1     abafado.PoS=Adj  TG=HUM:N0  POL:N0=-1  ANOT=JALC  NaN NaN
2    abafante.PoS=Adj  TG=HUM:N0  POL:N0=-1   ANOT=MAN  NaN NaN
3    abaixado.PoS=Adj  TG=HUM:N0  POL:N0=-1  ANOT=JALC  NaN NaN
4     abalado.PoS=Adj  TG=HUM:N0  POL:N0=-1  ANOT=JALC  NaN NaN
..                ...        ...        ...        ...  ...  ..
95     aceito.PoS=Adj  TG=HUM:N0   POL:N0=0  ANOT=JALC  NaN NaN
96  acelerado.PoS=Adj  TG=HUM:N0   POL:N0=0   ANOT=MAN  NaN NaN
97  acentuado.PoS=Adj  TG=HUM:N0   POL:N0=0  ANOT=JALC  NaN NaN
98    acerado.PoS=Adj  TG=HUM:N0  POL:N0=-1   ANOT=MAN  NaN NaN
99   acerbidade.PoS=N  TG=HUM:N0  POL:N0=-1   ANOT=MAN  NaN NaN

[100 rows x 6 columns]

In [10]:
# apagar colunas desnecessárias deixar apenas coluna 0 (palavras) e coluna 2 (polaridade)
df = df.drop(['a','b','x','y'], axis=1)
df.head()

            palavra polaridade
0   à-vontade.PoS=N   POL:N0=1
1   abafado.PoS=Adj  POL:N0=-1
2  abafante.PoS=Adj  POL:N0=-1
3  abaixado.PoS=Adj  POL:N0=-1
4   abalado.PoS=Adj  POL:N0=-1

In [11]:
#aplicar função split nas colunas Palavras e Polaridade
df['palavra']=df['palavra'].apply(lambda x: x.split('.'))
df['polaridade']=df['polaridade'].apply(lambda x: x.split('='))
df.head()

               palavra    polaridade
0   [à-vontade, PoS=N]   [POL:N0, 1]
1   [abafado, PoS=Adj]  [POL:N0, -1]
2  [abafante, PoS=Adj]  [POL:N0, -1]
3  [abaixado, PoS=Adj]  [POL:N0, -1]
4   [abalado, PoS=Adj]  [POL:N0, -1]

In [12]:
# Limpar as listas dos campos palavra e polaridade deixando apenas o importante
df['palavra']=df['palavra'].apply(lambda x: x[0])
df['polaridade']=df['polaridade'].apply(lambda x: x[1])
df.head()

     palavra polaridade
0  à-vontade          1
1    abafado         -1
2   abafante         -1
3   abaixado         -1
4    abalado         -1

In [ ]:
# info()
df.info()

In [13]:
#converter o campo polaridade para int
df['polaridade'] = df['polaridade'].astype(int)

In [14]:
#criar um dicionário com as colunas palavra (key) polaridade (value) utilizndo a função zip.
dic = dict(zip(df['palavra'],df['polaridade']))
dic

{'à-vontade': 1,
 'abafado': -1,
 'abafante': -1,
 'abaixado': -1,
 'abalado': -1,
 'abalizado': 1,
 'abalroado': -1,
 'abalroar': 1,
 'abanar': 1,
 'abandalhado': -1,
 'abandalhamento': -1,
 'abandonado': -1,
 'abandonar': -1,
 'abarcante': 0,
 'abarrotado': -1,
 'abastado': 1,
 'abastecido': 0,
 'abater': 1,
 'abatido': -1,
 'abelhudo': -1,
 'abençoado': 1,
 'aberração': -1,
 'aberrante': -1,
 'aberrativo': -1,
 'aberto': 1,
 'abespinhado': -1,
 'abestalhado': -1,
 'abilolado': -1,
 'abjeção': -1,
 'abjecção': -1,
 'abjecto': -1,
 'abjeto': -1,
 'abnegado': 1,
 'abobado': -1,
 'abobalhado': -1,
 'abolicionista': 0,
 'abolido': -1,
 'abominador': -1,
 'abominando': -1,
 'abominar': 0,
 'abominável': -1,
 'abonado': 1,
 'abonatório': 1,
 'abonecado': 0,
 'aborrecer-se': -1,
 'aborrecer': 1,
 'aborrecido': -1,
 'abortado': -1,
 'abraçado': 1,
 'abrasileirado': 0,
 'abrigado': 0,
 'abrilhantado': 1,
 'abrir a alma': 1,
 'abrir o coração': 1,
 'abrir os olhos': 1,
 'abrupto': -1,
 'abrutalhado': -1,
 'absentista': -1,
 'absolutista': 0,
 'absoluto': 0,
 'absolvido': 0,
 'absorvente': 1,
 'abstémico': 1,
 'abstémio': 1,
 'abstencionista': 0,
 'abstinente': 0,
 'abstracto': -1,
 'abstraído': -1,
 'abstrato': -1,
 'abstrusidade': -1,
 'abstruso': -1,
 'absurdo': -1,
 'abulia': -1,
 'abúlico': -1,
 'aburguesado': 0,
 'abusado': -1,
 'abusador': -1,
 'abusar': -1,
 'abusivo': -1,
 'acabado': -1,
 'acabadote': -1,
 'acabrunhado': -1,
 'acaciano': -1,
 'acadêmico': 0,
 'acalorado': 0,
 'açambarcador': -1,
 'acanhado': -1,
 'acanhamento': -1,
 'acanhar-se': -1,
 'acatado': 1,
 'acatador': 0,
 'acautelado': 0,
 'acéfalo': -1,
 'aceitável': 1,
 'aceite': 0,
 'aceito': 0,
 'acelerado': 0,
 'acentuado': 0,
 'acerado': -1,
 'acerbidade': -1,
 'acerbo': -1,
 'acérrimo': -1,
 'acertado': 1,
 'acertar na mosca': 1,
 'acertar na mouche': 1,
 'aceso': 0,
 'acessível': 1,
 'achacado': -1,
 'achado': 0,
 'achar piada a': 0,
 'achatado': -1,
 'achegado': 1,
 'achincalhar': -1,
 'achinesado': 0,
 'acidentado': -1,
 'aciganado': -1,
 'acintoso': -1,
 'acirrado': -1,
 'aclamado': 0,
 'aclamar': 0,
 'acobardado': -1,
 'acobardar-se': -1,
 'acobertado': -1,
 'acobreado': 0,
 'acocado': -1,
 'açoitado': -1,
 'acolhedor': 1,
 'acolhido': 0,
 'acomodadiço': -1,
 'acomodar-se': -1,
 'acomodatício': 0,
 'acompanhado': 0,
 'acompanhador': 0,
 'acompanhante': 0,
 'aconchegado': 1,
 'acordado': 0,
 'acordar com o rabo para o ar': -1,
 'acordar com os pés de fora': -1,
 'acorrentado': -1,
 'acorrentar-se': -1,
 'acorrentar': 1,
 'acossado': -1,
 'acossar': 1,
 'acostumado': 0,
 'acotovelar': 0,
 'açougueiro': -1,
 'acre': -1,
 'acreditado': 1,
 'acreditar': 0,
 'acriançado': -1,
 'acrisolado': 0,
 'acrítico': -1,
 'activo': 1,
 'actualista': 0,
 'acudir': 1,
 'aculturado': -1,
 'acurado': 1,
 'acusado': -1,
 'acusar': 0,
 'acutilante': -1,
 'adâmico': -1,
 'adaptado': 0,
 'adepto': 1,
 'adequado': 1,
 'adestrado': 1,
 'adicional': 0,
 'adiposo': -1,
 'adjacente': 0,
 'administrado': 0,
 'admirar': 0,
 'admirável': 1,
 'admitido': 0,
 'admoestador': -1,
 'adoentado': -1,
 'adorado': 1,
 'adorando': 1,
 'adorar': 0,
 'adorável': 1,
 'adormecido': -1,
 'adulador': -1,
 'adulterador': -1,
 'adulterino': -1,
 'adultério': -1,
 'adúltero': -1,
 'adulto': 0,
 'adventista': 0,
 'adverso': -1,
 'aéreo': -1,
 'afabilidade': 1,
 'afamado': 1,
 'afanado': -1,
 'afasia': -1,
 'afásico': -1,
 'afastar': 0,
 'afável': 1,
 'afectado': -1,
 'afectar': 0,
 'afectividade': 1,
 'afectivo': 1,
 'afecto': 1,
 'afectuoso': 1,
 'afeiçoado': 1,
 'afeito': 0,
 'afeminado': -1,
 'aferido': 0,
 'aferrado': 0,
 'afetado': -1,
 'afetividade': 1,
 'afetivo': 1,
 'afeto': 1,
 'afetuoso': 1,
 'afiado': -1,
 'afidalgado': 0,
 'afilado': 0,
 'afilhado': 0,
 'afinado': 1,
 'afincado': 0,
 'afirmativo': 1,
 'aflição': -1,
 'afligido': -1,
 'afligir-se': -1,
 'afligir': 0,
 'aflitivo': -1,
 'aflito': -1,
 'afobado': -1,
 'afogado': -1,
 'afogar as mágoas': -1,
 'afogar-se em pouca água': -1,
 'afogar-se': -1,
 'afogueado': 0,
 'afoiteza': 1,
 'afoito': 1,
 'afortunado': 1,
 'afrancesado': 0,
 'afrontado': -1,
 'afrontar': 1,
 'afrontoso': -1,
 'afugentar': 1,
 'afundado': -1,
 'afundanço': -1,
 'afundar-se': -1,
 'afundar': 1,
 'agachado': -1,
 'agarotado': -1,
 'agarrado': -1,
 'agarrar a oportunidade com unhas e dentes': 1,
 'agarrar a oportunidade': 1,
 'agarrar o touro pelos cornos': 1,
 'agarrar-se ao poder': -1,
 'agasalhado': 0,
 'agastadiço': -1,
 'agastado': -1,
 'agastar-se': -1,
 'ágil': 1,
 'agilidade': 1,
 'agiota': -1,
 'agir de boa-fé': 1,
 'agir de má-fé': -1,
 'aglomerado': 0,
 'agnóstico': 0,
 'agoirento': -1,
 'agonia': -1,
 'agoniado': -1,
 'agoniante': -1,
 'agoniar': -1,
 'agonizante': -1,
 'agoureiro': -1,
 'agourento': -1,
 'agradado': 1,
 'agradar': 1,
 'agradável': 1,
 'agradecer': 0,
 'agrado': 1,
 'agravado': -1,
 'agravar': -1,
 'agre': -1,
 'agredir': -1,
 'agregado': 0,
 'agressividade ': -1,
 'agressivo': -1,
 'agressor': -1,
 'agreste': -1,
 'agrilhoado': -1,
 'agrosseirado': -1,
 'aguado': -1,
 'aguardado': 0,
 'aguçado': -1,
 'agudo': 0,
 'aguentar-se bem': 1,
 'aguentar-se': 1,
 'aguerrido': 0,
 'airoso': 1,
 'ajanotado': 0,
 'ajudado': 1,
 'ajuizado': 1,
 'alapado': -1,
 'alarmante': -1,
 'alarmismo': -1,
 'alarmista': -1,
 'alarve': -1,
 'alarvice': -1,
 'albigense': 0,
 'albino': -1,
 'alcandorado': 0,
 'alcoólatra': -1,
 'alcoólico': -1,
 'alcoolismo': -1,
 'alcoolizado': -1,
 'alcunhado': 0,
 'aldrabão': -1,
 'alegado': -1,
 'alegrar-se': 1,
 'alegre': 1,
 'alegrete': 0,
 'alegria': 1,
 'alegrote': 0,
 'aleijado': -1,
 'aleivoso': -1,
 'alentado': 1,
 'alentador': 1,
 'alento': 1,
 'alérgico': 0,
 'alfabetizado': 0,
 'algemado': -1,
 'alheado': -1,
 'alhear-se': -1,
 'alheio': -1,
 'aliado': 0,
 'alicerçado': 1,
 'aliciado': -1,
 'aliciar': -1,
 'alienação mental': -1,
 'alienado': -1,
 'alienígena': -1,
 'aligeirado': 0,
 'alimentado': 0,
 'alinhado': 1,
 'aliviado': 0,
 'almo': 1,
 'almóada': 0,
 'almorávida': 0,
 'aloirado': 0,
 'alourado': 0,
 'alquebrado': -1,
 'altamente': 1,
 'altaneiro': -1,
 'alteroso': 0,
 'altivo': -1,
 'alto': 0,
 'altruísmo': 1,
 'altruísta': 1,
 'altruístico': 1,
 'aluado': -1,
 'alucinação': -1,
 'alucinado': -1,
 'alucinar': -1,
 'alumbrado': -1,
 'alumiado': 1,
 'alvejado': 0,
 'alvissareiro': 0,
 'alvoraçado': -1,
 'amabilidade': 1,
 'amachucado': -1,
 'amachucar': 1,
 'amado': 1,
 'amador': 0,
 'amadorismo': -1,
 'amadurecer': 1,
 'amadurecido': 1,
 'amaldiçoado': -1,
 'amalucado': -1,
 'amamentado': 0,
 'amaneirado': -1,
 'amar': 0,
 'amarelado': -1,
 'amarelo': -1,
 'amargado': -1,
 'amargo': -1,
 'amargura': -1,
 'amargurado': -1,
 'amaricado': -1,
 'amarrado': -1,
 'amassado': -1,
 'amável': 1,
 'ambicioso': 0,
 'ambidestro': 0,
 'ambidextro': 0,
 'ambiguidade': -1,
 'ambíguo': -1,
 'ambiopia': -1,
 'ambliopia': -1,
 'ambrosiano': 0,
 'ameaça': -1,
 'ameaçador': -1,
 'ameaçante': -1,
 'amedrontado': -1,
 'amedrontador': -1,
 'amedrontar': 1,
 'ameno': 1,
 'americanista': 0,
 'americanófilo': 0,
 'americanófobo': -1,
 'amestrado': 1,
 'amigalhaço': 1,
 'amigalhão': 1,
 'amigável': 1,
 'amigo da onça': -1,
 'amigo da pinga': -1,
 'amigo dos copos': -1,
 'amigo': 1,
 'amistoso': 1,
 'amnésia': -1,
 'amnésico': -1,
 'amolecer': -1,
 'amoral': -1,
 'amoralidade': -1,
 'amoralista': -1,
 'amorável': 1,
 'amorfia': -1,
 'amorfo': -1,
 'amorosidade': 1,
 'amoroso': 1,
 'amortecido': -1,
 'amotinado': -1,
 'amputado': -1,
 'amuado': -1,
 'amuamento': -1,
 'amuar': -1,
 'amuo': -1,
 'anacrónico': -1,
 'anacrônico': -1,
 'anafado': -1,
 'analfabeto': -1,
 'analisador': 0,
 'analista': 0,
 'anão': -1,
 'anárquico': -1,
 'anarquista': -1,
 'ancião': 0,
 'andante': -1,
 'andar a apanhar bonés': -1,
 'andar à deriva': -1,
 'andar a dormir à sombra da bananeira': -1,
 'andar a dormir': -1,
 'andar a falar sozinho': -1,
 'andar à nora': -1,
 'andar a pensar na morte da bezerra': -1,
 'andar a reboque de': -1,
 'andar à sombra da bananeira': -1,
 'andar ao deus dará': -1,
 'andar aos bonés': -1,
 'andar aos caídos': -1,
 'andar aos papéis': -1,
 'andar armado em carapau de corrida': -1,
 'andar às aranhas': -1,
 'andar às cavalitas de': -1,
 'andar às cegas': -1,
 'andar às turras com': -1,
 'andar com a cabeça na lua': -1,
 'andar com cara de caso': -1,
 'andar com dor de corno': -1,
 'andar com dor de cotovelo': -1,
 'andar com macacos na cabeça': -1,
 'andar com macacos no sótão': -1,
 'andar com macaquinhos na cabeça': -1,
 'andar com macaquinhos no sótão': -1,
 'andar com o coração nas mãos': -1,
 'andar com os azeites': -1,
 'andar de olhos vendados': -1,
 'andar de trombas': -1,
 'andar em pele e osso': -1,
 'andar feito barata tonta': -1,
 'andar feito com': -1,
 'andar na boa vida': -1,
 'andar na lua': -1,
 'andar na má vida': -1,
 'andar nas sete quintas': 1,
 'andar pelos cabelos': -1,
 'andarilho': 0,
 'andrajoso': -1,
 'anedótico': -1,
 'anémico': -1,
 'anêmico': -1,
 'anestesiado': -1,
 'anestesiar': 1,
 'anexado': 0,
 'anexionista': 0,
 'angelical': 1,
 'angélico': 1,
 'angelita': 0,
 'anglicano': 0,
 'anglófilo': 0,
 'anglófobo': -1,
 'angustiado': -1,
 'angustiante': -1,
 'angustiar': 0,
 'animação': 1,
 'animado': 1,
 'animador': 1,
 'animal político': 1,
 'animal': -1,
 'animar': 1,
 'animista': 0,
 'animosidade': -1,
 'animoso': 1,
 'aniquilado': -1,
 'aniquilar': 1,
 'anjinho': -1,
 'anómalo': -1,
 'anoréctico': -1,
 'anorético': -1,
 'anorexia nervosa': -1,
 'anorexia': -1,
 'anormal': -1,
 'anormalidade': -1,
 'anotia': -1,
 'ansioso': -1,
 'antepassado': 0,
 'anti-republicano': -1,
 'antidemocrata': -1,
 'antidesportista': -1,
 'antidesportivismo': -1,
 'antidogmático': 1,
 'antifascista': 1,
 'antifederalista': 0,
 'antigo': 0,
 'antiliberal': -1,
 'antiliberalista': -1,
 'antimilitarista': 0,
 'antinatural': -1,
 'antinazista': 1,
 'antinómico': -1,
 'antipapista': 0,
 'antipartidário': 0,
 'antipatia': -1,
 'antipático': -1,
 'antipatriota': -1,
 'antipatriotismo': -1,
 'antipolítico': -1,
 'antiquado': -1,
 'antisocial': -1,
 'antoniano': 0,
 'antonino': 0,
 'antropófago': -1,
 'anular': 1,
 'apadrinhado': 0,
 'apagado': -1,
 'apagar-se': -1,
 'apagar': 1,
 'apaixonado': 0,
 'apaixonante': 1,
 'apaixonar-se': 0,
 'apaixonar': 1,
 'apalavrado': 0,
 'apalermado': -1,
 'apalhaçado': -1,
 'apancado': -1,
 'apanhado': -1,
 'apanhar nas orelhas': -1,
 'apanhar por tabela': -1,
 'apaparicar': -1,
 'aparolado': -1,
 'apartado': -1,
 'aparvalhado': -1,
 'apatetado': -1,
 'apatia': -1,
 'apático': -1,
 'apatriota': -1,
 'apavorado': -1,
 'apavorante': -1,
 'apavorar-se': -1,
 'apavorar': 1,
 'apaziguador': 1,
 'apaziguar': 1,
 'apeado': -1,
 'apedantado': -1,
 'apedrejado': -1,
 'apedrejar': -1,
 'apelativo': 1,
 'apele': 0,
 'apelidado': 0,
 'aperaltado': -1,
 'aperreado': -1,
 'apessoado': 1,
 'apetitoso': 0,
 'aplaudir': 0,
 'aplicado': 1,
 'aplicar golpes baixos a': -1,
 'apócrifo': -1,
 'apoiar': 0,
 'apolíneo': 1,
 'apologético': 0,
 'apopléctico': -1,
 'apoplético': -1,
 'apoquentado': -1,
 'apoquentador': -1,
 'aposentado': 0,
 'apostado': 1,
 'apóstata': -1,
 'aprazível': 1,
 'apreciado': 1,
 'apreciador': 1,
 'apreciar': 0,
 'apreciável': 1,
 'apreendido': -1,
 'apreensivo': -1,
 'apresentar alternativas': 1,
 'apresentar resultados': 1,
 'apresentável': 1,
 'apressado': 0,
 'aprimorado': 1,
 'apriorista': -1,
 'aprisionado': -1,
 'aprontado': 0,
 'aprontar': -1,
 'apropriado': 1,
 'apropriar-se': -1,
 'aprovado': 1,
 'aproveitador': -1,
 'aproveitar-se': -1,
 'aprumado': 1,
 'aprumo': 1,
 'apto': 1,
 'apunhalado': -1,
 'apunhalar pelas costas': -1,
 'apunhalar': -1,
 'apupar': 0,
 'apurado': 1,
 'aquietador': -1,
 'árabe': 0,
 'arbitrário': -1,
 'arcaico': -1,
 'ardente': 1,
 'ardil': -1,
 'ardiloso': -1,
 'ardoroso': 0,
 'árduo': -1,
 'arfante': -1,
 'arguto': 0,
 'ariano': 0,
 'árido': -1,
 'arisco': -1,
 'aristocrata': 0,
 'aristotélico': 0,
 'armado': 0,
 'armar barraca': -1,
 'armar-se aos cágados': -1,
 'armar-se aos cucos': -1,
 'armar-se em carapau de corrida': -1,
 'armar-se em chico esperto': -1,
 'armar-se em parvo': -1,
 'armar-se': -1,
 'arnaz': 1,
 'arquejante': -1,
 'arrancado': 0,
 'arranhado': -1,
 'arranjar lenha para se queimar': -1,
 'arranjar sarna para se coçar': -1,
 'arranjar um bico de obra': -1,
 'arrasado': -1,
 'arrasador': 0,
 'arrasante': 0,
 'arrasar': 1,
 'arrastadeiro': -1,
 'arrastado': -1,
 'arrebatado': 0,
 'arrebatador': 0,
 'arrebatar': 1,
 'arrebentado': -1,
 'arrebitado': -1,
 'arredado': -1,
 'arredio': -1,
 'arreliado': -1,
 'arreliador': -1,
 'arreliar': 1,
 'arremessado': 0,
 'arrenegado': -1,
 'arrepender-se': -1,
 'arrepiante': -1,
 'arrepio': -1,
 'arretado': 1,
 'arrevesado': -1,
 'arrivista': -1,
 'arrogância': -1,
 'arrogante': -1,
 'arrojado': 1,
 'arrolado': -1,
 'arrozeiro': 0,
 'arruaceiro': -1,
 'arrufado': -1,
 'arrufo': -1,
 'arruinado': -1,
 'arruinamento': -1,
 'arruinar-se': -1,
 'arruinar': -1,
 'arruivado': 0,
 'arrumar a um canto': 1,
 'arrumar as botas': -1,
 'arrumar': 1,
 'arteirice': -1,
 'arteiro': -1,
 'arteriosclerose': -1,
 'arteriosclerótico': -1,
 'artificial': -1,
 'artificialidade': -1,
 'artifício': -1,
 'artificiosidade': -1,
 'artificioso': -1,
 'artimanha': -1,
 'artista': 0,
 'artístico': 1,
 'artritismo': -1,
 'ascético': 0,
 'aselha': -1,
 'aselhice': -1,
 'asfixiante': -1,
 'asfixiar': 1,
 'asilado': -1,
 'asneira': -1,
 'asneirento': -1,
 'asno': -1,
 'aspereza': -1,
 'áspero': -1,
 'aspirante': 0,
 'asquerosidade': -1,
 'asqueroso': -1,
 'assalariado': -1,
 'assaloiado': -1,
 'assaltante': -1,
 'assaltar': -1,
 'assanhadiço': -1,
 'assanhado': -1,
 'assarapantado': -1,
 'assassinar': -1,
 'assassino': -1,
 'assaz': 0,
 'asseado': 1,
 'assediado': -1,
 'assediador': -1,
 'assediar': -1,
 'assédio sexual': -1,
 'assédio': -1,
 'asseio': 1,
 'assertivo': 1,
 'assexuado': 0,
 'assexual': 0,
 'assiduidade': 1,
 'assíduo': 1,
 'assimétrico': -1,
 'assimilado': 0,
 'assinado': 0,
 'assinalado': 1,
 'assinalável': 1,
 'assisado': 1,
 'assoberbado': -1,
 'assolado': -1,
 'assolador': -1,
 'assomadiço': -1,
 'assombrado': -1,
 'assombrar': 1,
 'assustadiço': -1,
 'assustado': -1,
 'assustador': -1,
 'assustar-se': -1,
 'assustar': 0,
 'astenia': -1,
 'asténico': -1,
 'astúcia': -1,
 'astucioso': -1,
 'astuto': -1,
 'atabalhoação': -1,
 'atabalhoado': -1,
 'atabalhoamento': -1,
 'atacante': -1,
 'atacar': 1,
 'atado': -1,
 'atafulhado': -1,
 'atamancado': -1,
 'atarantação': -1,
 'atarantado': -1,
 'atarantar-se': -1,
 'atarantar': 1,
 'atarefado': 0,
 'atarracado': -1,
 'atascado': 0,
 'ateado': -1,
 'atemorizado': -1,
 'atemorizar': 1,
 'atencioso': 1,
 'atento': 1,
 'aterrado': -1,
 'aterrador': -1,
 'aterrorizado': -1,
 'aterrorizador': -1,
 'aterrorizar': 1,
 'atiçado': 0,
 'atilado': 1,
 'atinado': 1,
 'atiradiço': 0,
 'atirar areia para os olhos de': -1,
 'atirar barro à parede': -1,
 'atirar com as culpas a': -1,
 'atirar poeira aos olhos de': -1,
 'ativado': 0,
 'ativo': 1,
 'atleta': 1,
 'atlético': 1,
 'atoleimado': -1,
 'atónito': -1,
 'atônito': -1,
 'atordoado': -1,
 'atordoador': -1,
 'atordoar': 1,
 'atormentado': -1,
 'atormentador': -1,
 'atormentar': 1,
 'atracado': -1,
 'atractivo': 1,
 'atraente': 1,
 'atraiçoado': -1,
 'atrair': 1,
 'atrapalhado': -1,
 'atrapalhar-se': -1,
 'atrapalhar': 1,
 'atrasado mental': -1,
 'atrasado': -1,
 'atraso mental': -1,
 'atraso': -1,
 'atrativo': 1,
 'atravessadiço': -1,
 'atravessado': -1,
 'atrevido': 0,
 'atrevidote': 0,
 'atribulado': -1,
 'atroador': -1,
 'atrocidade': -1,
 'atrofia': -1,
 'atrofiado': -1,
 'atrofiante': -1,
 'atrofiar-se': -1,
 'atrofiar': -1,
 'atropelado': -1,
 'atropelar': -1,
 'atroz': -1,
 'atulhado': -1,
 'aturar': 0,
 'aturdido': -1,
 'aturdir': 1,
 'audacioso': 0,
 'audaz': 0,
 'áureo': 1,
 'auspicioso': 1,
 'austero': -1,
 'autenticidade': 1,
 'autêntico': 1,
 'autismo': -1,
 'autista': -1,
 'autoconfiança': 1,
 'autoconfiante': 1,
 'autocrata': 0,
 'autodestruição': -1,
 'autodestrutivo': -1,
 'autodidacta': 1,
 'autodidata': 1,
 'autonomia': 1,
 'autonomista': 1,
 'autónomo': 1,
 'autoritário': -1,
 'autoritarismo': -1,
 'autorizado': 1,
 'autosuficiência': 1,
 'autosuficiente': 1,
 'auxiliado': 0,
 'avançado': 1,
 'avantajado': 0,
 'avarento': -1,
 'avareza': -1,
 'avariado': -1,
 'avariar': -1,
 'avaro': -1,
 'avassalador': -1,
 'avassalamento': -1,
 'avassalante': -1,
 'avassalar': 1,
 'avençado': 0,
 'aventurado': 0,
 'aventureiro': 0,
 'aventuroso': 0,
 'averiguador': 0,
 'avermelhado': 0,
 'averroísta': 0,
 'averso': -1,
 'avesso': -1,
 'ávido': -1,
 'aviltado': -1,
 'aviltador': -1,
 'aviltante': -1,
 'avinagrado': -1,
 'avinhado': -1,
 'avisado': 1,
 'avulso': -1,
 'azafamado': -1,
 'azambrado': -1,
 'azar': -1,
 'azarado': -1,
 'azarento': -1,
 'azedar': -1,
 'azedo': -1,
 'azedume': -1,
 'azeiteiro': -1,
 'azelha': -1,
 'azelhice': -1,
 'azoinante': -1,
 'azougado': -1,
 'babaca': -1,
 'babão': -1,
 'babilónico': -1,
 'baboseira': -1,
 'babosice': -1,
 'baboso': -1,
 'bacano': 1,
 'baço para espelho': -1,
 'bacoco': -1,
 'baconiano': 0,
 'bacoquice': -1,
 'badalhoco': -1,
 'badalhoquice': -1,
 'bagaceiro': -1,
 'bagunceiro': -1,
 'bairrista': 0,
 'baixeza': -1,
 'baixote': -1,
 'bajulador': -1,
 'bajular': -1,
 'balbuciante': -1,
 'balofice': -1,
 'balofo': -1,
 'bambo': -1,
 'banal': -1,
 'banalidade': -1,
 'banalizar': -1,
 'banana': -1,
 'bancarrota': -1,
 'bandido': -1,
 'banditismo': -1,
 'banhado': 0,
 'banido': -1,
 'banir': 1,
 'banzado': -1,
 'barafustar': 0,
 'baralhado': -1,
 'baralhar-se': -1,
 'baralhar': 0,
 'barateiro': 0,
 'barato': -1,
 'barbado': 0,
 'barbaridade': -1,
 'bárbaro': -1,
 'barbeado': 0,
 'barbilongo': 0,
 'barbudo': 0,
 'barrado': -1,
 'barraqueiro': -1,
 'barrigana': -1,
 'barrigudo': -1,
 'barroco': -1,
 'barulhento': -1,
 'baselga': -1,
 'básico': -1,
 'bastardo': -1,
 'basto': 0,
 'batalhador': 1,
 'batalhante': 1,
 'batalhar': 1,
 'batateiro': 0,
 'batatudo': -1,
 'bater a bota': -1,
 'bater as botas': -1,
 'bater com o nariz na porta': -1,
 'bater no ceguinho': -1,
 'bater no fundo': -1,
 'bater': 1,
 'batido': -1,
 'batota': -1,
 'batoteiro': -1,
 'batotice': -1,
 'bazófia': -1,
 'bazófio': -1,
 'beatice': -1,
 'beato': -1,
 'bêbado': -1,
 'bebedeira': -1,
 'bêbedo': -1,
 'bebedor': -1,
 'beberrão': -1,
 'bebido': -1,
 'bebum': -1,
 'beiçudo': -1,
 'beijoqueiro': 0,
 'beleza': 1,
 ...}

In [15]:
#testar o retorno de alguma chave do dicionario
dic.get('sincero', "não encontrado")

1

In [16]:
# tranformar a frase para minúscula
frase = 'eu, Nilton, estou super feliz hoje, empolgado, com o trabalho dos meus Queridos alunos!!'
#letras maiúsculas
#acentuação
#stopwords

In [17]:
    #transformando a frase em letras minúsculas
    frase = frase.lower()
    frase

'eu, nilton, estou super feliz hoje, empolgado, com o trabalho dos meus queridos alunos!!'

In [19]:
# importar biblioteca string e a lista string.ponctuation e excluir a pontuação
# usar list comprehensions e método join
import string
pontuacao = string.punctuation
x = [i for i in frase if i not in pontuacao]
x
frase = ''.join([i for i in frase if i not in pontuacao])
frase

'eu nilton estou super feliz hoje empolgado com o trabalho dos meus queridos alunos'

In [23]:
# importando a bliblioteca nltk.corpus (NLP)
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
stopwords = stopwords.words('portuguese')
stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

['a',
 'à',
 'ao',
 'aos',
 'aquela',
 'aquelas',
 'aquele',
 'aqueles',
 'aquilo',
 'as',
 'às',
 'até',
 'com',
 'como',
 'da',
 'das',
 'de',
 'dela',
 'delas',
 'dele',
 'deles',
 'depois',
 'do',
 'dos',
 'e',
 'é',
 'ela',
 'elas',
 'ele',
 'eles',
 'em',
 'entre',
 'era',
 'eram',
 'éramos',
 'essa',
 'essas',
 'esse',
 'esses',
 'esta',
 'está',
 'estamos',
 'estão',
 'estar',
 'estas',
 'estava',
 'estavam',
 'estávamos',
 'este',
 'esteja',
 'estejam',
 'estejamos',
 'estes',
 'esteve',
 'estive',
 'estivemos',
 'estiver',
 'estivera',
 'estiveram',
 'estivéramos',
 'estiverem',
 'estivermos',
 'estivesse',
 'estivessem',
 'estivéssemos',
 'estou',
 'eu',
 'foi',
 'fomos',
 'for',
 'fora',
 'foram',
 'fôramos',
 'forem',
 'formos',
 'fosse',
 'fossem',
 'fôssemos',
 'fui',
 'há',
 'haja',
 'hajam',
 'hajamos',
 'hão',
 'havemos',
 'haver',
 'hei',
 'houve',
 'houvemos',
 'houver',
 'houvera',
 'houverá',
 'houveram',
 'houvéramos',
 'houverão',
 'houverei',
 'houverem',
 'houveremos',
 'houveria',
 'houveriam',
 'houveríamos',
 'houvermos',
 'houvesse',
 'houvessem',
 'houvéssemos',
 'isso',
 'isto',
 'já',
 'lhe',
 'lhes',
 'mais',
 'mas',
 'me',
 'mesmo',
 'meu',
 'meus',
 'minha',
 'minhas',
 'muito',
 'na',
 'não',
 'nas',
 'nem',
 'no',
 'nos',
 'nós',
 'nossa',
 'nossas',
 'nosso',
 'nossos',
 'num',
 'numa',
 'o',
 'os',
 'ou',
 'para',
 'pela',
 'pelas',
 'pelo',
 'pelos',
 'por',
 'qual',
 'quando',
 'que',
 'quem',
 'são',
 'se',
 'seja',
 'sejam',
 'sejamos',
 'sem',
 'ser',
 'será',
 'serão',
 'serei',
 'seremos',
 'seria',
 'seriam',
 'seríamos',
 'seu',
 'seus',
 'só',
 'somos',
 'sou',
 'sua',
 'suas',
 'também',
 'te',
 'tem',
 'tém',
 'temos',
 'tenha',
 'tenham',
 'tenhamos',
 'tenho',
 'terá',
 'terão',
 'terei',
 'teremos',
 'teria',
 'teriam',
 'teríamos',
 'teu',
 'teus',
 'teve',
 'tinha',
 'tinham',
 'tínhamos',
 'tive',
 'tivemos',
 'tiver',
 'tivera',
 'tiveram',
 'tivéramos',
 'tiverem',
 'tivermos',
 'tivesse',
 'tivessem',
 'tivéssemos',
 'tu',
 'tua',
 'tuas',
 'um',
 'uma',
 'você',
 'vocês',
 'vos']

In [20]:
#transformar a frase em uma lista de palavras com .split()
frase = frase.split()
frase

['eu',
 'nilton',
 'estou',
 'super',
 'feliz',
 'hoje',
 'empolgado',
 'com',
 'o',
 'trabalho',
 'dos',
 'meus',
 'queridos',
 'alunos']

In [24]:
# retirar as stopwords do frase
frase = [i for i in frase if i not in stopwords]
frase

['nilton',
 'super',
 'feliz',
 'hoje',
 'empolgado',
 'trabalho',
 'queridos',
 'alunos']

In [25]:
#calcular o score da frase
lista = [dic.get(i,0) for i in frase]
lista
print(sum(lista))

2

In [39]:
import string
pontuacao = string.punctuation
def Sentimento(frase,ic):
  frase.lower()
  frase = "".join([i for i in frase if i not in pontuacao])
  print(frase)
  frase = [i for i in frase.split() if i not in stopwords]
  print(frase)
  lista = [dic.get(i,0) for i in frase]
  print(lista)
  score = sum(lista)
  print(score)

frase = 'eu, Nilton, estou super feliz hoje, mas estou atrapalhado, entretanto, as coisas não estão boas, estão indo muito mal mas estou empolgado, com o trabalho dos meus Queridos alunos!!'
Sentimento(frase,dic)

eu Nilton estou super feliz hoje mas estou atrapalhado entretanto as coisas não estão boas estão indo muito mal mas estou empolgado com o trabalho dos meus Queridos alunos
['Nilton', 'super', 'feliz', 'hoje', 'atrapalhado', 'entretanto', 'coisas', 'boas', 'indo', 'mal', 'empolgado', 'trabalho', 'Queridos', 'alunos']
[0, 0, 1, 0, -1, 0, 0, 0, 0, 0, 1, 0, 0, 0]
1